spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.vumrokofxrpletxahxjl&password=7ErhEwSEWZEQBBxL


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
